### ISSUE TITLE
Quiver in plot_current25.py does not work

### ISSUE THREAD

**Issue by javadbabagoli** [bjornaa/roppy#1]
Hi 
Thanks for your code!
I try to use your code for ROMS plot. I can use some of them but I cannot quiver in  plot_current25.py

The code ran successfully and gave me a map but do not show any vector.

Is it possible to check out and mention what happens?

**Comment by bjornaa** [comment]
Hi Javadbabagoli,

Thanks for your interest.

The useless answer is "it works for me". I attach the image from the example as it should come out.

Did you try the example with the example file from ftp?
If that does not work, it is hard to say what goes wrong.

If you tried it on a ROMS file of your own, put the file on a server where I can download it and email me your script.
I can then try to recreate the issue and find out what goes wrong.

Bjørn Ådlandsvik
e-mail: ***@***.***

________________________________________
Fra: javadbabagoli ***@***.***>
Sendt: mandag 14. august 2023 18.04
Til: bjornaa/roppy
Kopi: Subscribed
Emne: [bjornaa/roppy] Quiver in plot_current25.py does not work (Issue #1)

Hi
Thanks for your code!
I try to use your code for ROMS plot. I can use some of them but I cannot quiver in plot_current25.py

The code ran successfully and gave me a map but do not show any vector.

Is it possible to check out and mention what happens?

**Comment by bjornaa** [comment]
The issue is the scale argument to quiver.
I have not been able to find a reasonable default.
It depends on the grid size, the size of the plot area, the stride, ...
I will add a comment on the need for some experimenting with this argument.

Bjørn Å.
